version: 2
jobs:
  build:
    working_directory: ~/sample
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - run:
          name: コードの取得
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: 独自コンテナで実行
          command: |
            node -v
      - run:
          name: node_modulesのインストール
          command: |
            yarn
  test:
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - run:
          name: テスト
          command: |
            yarn lint
