version: 2
jobs:
  build:
    working_directory: ~/sample
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - run:
          name: コードの取得
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: 独自コンテナで実行
          command: |
            node -v
      - run:
          name: node_modulesのインストール
          command: |
            yarn
      - run:
          name: テスト
          command: |
            yarn lint
      - run:
          name: ビルド
          command: |
            yarn run build
      - run:
          name: firebase-toolsのインストール
          command: |
            yarn global add firebase-tools
      - run:
          name: firebaseへデプロイ
          command: |
            ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
